#!/usr/bin/env python

import os
import platform

from naglib.nagiosplugin import NagiosPlugin, NAG_WARNING, NAG_CRITICAL, NAG_OK


class LinuxRelease(NagiosPlugin):
    VERSION = '1.0.2'
    HELP = """This is some more info on this specific plugin"""

    def workload(self):
        if platform.system() != 'Linux':
            self.exit(NAG_WARNING, 'This plugin is only meaningfull on Linux systems!')

        retcode, stdout, stderr = self.cmd_execute_output('lsb_release -a')
        if retcode:
            self.exit_crit('lsb_release command failed!')
        try:
            s = stdout.split('Description:')[1].split('Release:')[0]
            release_string = s.strip()
        except:
            self.exit_crit('Failed to parse release string')
        self.exit(NAG_OK, release_string)

if __name__ == "__main__":
    LinuxRelease().run()

